/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vaultSol from "./vault.sol";
export type { vaultSol };
export type { FLPCrowdSale } from "./FLPCrowdSale";
export type { Floppy } from "./Floppy";
export type { USDT } from "./USDT";
